# Generated by Django 4.1.4 on 2023-01-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text for the context')),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.TextField(help_text='Question JSON Schema')),
                ('text', models.TextField(help_text='Text for the question')),
                ('correct_response', models.TextField(help_text='Correct response JSON')),
                ('context', models.ForeignKey(help_text='Context for the questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dance.context')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('language', models.CharField(choices=[('KY', 'KYRGYZ'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], default='EN', max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('translations', models.ManyToManyField(blank=True, help_text='Translations of the word into other languages and synonyms', to='dance.word')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack', to='dance.learner')),
                ('words', models.ManyToManyField(blank=True, to='dance.word')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(help_text='Quiz questions', related_name='questions', to='dance.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='words',
            field=models.ManyToManyField(help_text='Words tested in the question', related_name='questions', to='dance.word'),
        ),
        migrations.AddField(
            model_name='learner',
            name='system',
            field=models.ForeignKey(help_text='System which Learner belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='Learners', to='dance.system'),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_type', models.CharField(choices=[('MQC', 'Correct answer to multiple choice question'), ('MQI', 'Incorrect answer to multiple choice question'), ('NQC', 'Correct answer to multiple choice quiz with choices in native language'), ('NQI', 'Incorrect answer to multiple choice quiz with choices in native language'), ('SQC', 'Correct answer to spelling quiz'), ('SQI', 'Incorrect answer to spelling quiz'), ('SFC', 'Word selected as familiar'), ('SFI', 'Word selected as unfamiliar'), ('SKC', 'Word selected as known'), ('SKI', 'Word selected as unknown')], max_length=4)),
                ('learner', models.ForeignKey(help_text='Learner who encountered the Word', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='dance.learner')),
                ('word', models.ForeignKey(help_text='Word encountered by Learner', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='dance.word')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('words', models.ManyToManyField(blank=True, to='dance.word')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MQ', 'Multiple choice quiz'), ('NQ', 'Multiple choice quiz with choices in native language'), ('SQ', 'Spelling quiz'), ('SF', 'Familiar selection'), ('SK', 'Known selection')], max_length=2)),
                ('questions', models.JSONField(default=dict, help_text='Questions in JSON Schema format')),
                ('uischema', models.JSONField(default=dict, help_text='UI schema for Questions in JSON Schema React Form format')),
                ('correct_answers', models.JSONField(default=dict, help_text='Correct answers in JSON format matching schema in Questions')),
                ('learner_answers', models.JSONField(default=dict, help_text='Answers by Learner in JSON format matching schema in Questions')),
                ('score', models.IntegerField(help_text='Percentage of correct responses', null=True)),
                ('test_language', models.CharField(choices=[('KY', 'KYRGYZ'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], default='EN', max_length=2)),
                ('native_language', models.CharField(choices=[('KY', 'KYRGYZ'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], default='EN', max_length=2)),
                ('regenerate_stack', models.BooleanField(default=False, help_text='Flag indicating that Stack Answrsheet is using to make questions should be regenerated')),
                ('collection', models.ForeignKey(blank=True, help_text='Selection of words that limits question generation for an Answersheet instance. If null, all words are considered for this particular user and language. Collection also influences which Stack is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dance.collection')),
                ('learner', models.ForeignKey(help_text='Responding Learner', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dance.learner')),
            ],
        ),
    ]
