# Generated by Django 4.1.4 on 2023-01-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text for the context')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.TextField(help_text='Question JSON Schema')),
                ('text', models.TextField(help_text='Text for the question')),
                ('correct_response', models.TextField(help_text='Correct response JSON')),
                ('context', models.ForeignKey(help_text='Context for the questions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dance.context')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='order',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.ManyToManyField(help_text='Quiz questions', related_name='questions', to='dance.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='words',
            field=models.ManyToManyField(help_text='Words tested in the question', related_name='questions', to='dance.word'),
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('system', models.ForeignKey(help_text='System which Learner belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='Learners', to='dance.system')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_type', models.CharField(choices=[('PC', 'Pure context'), ('QC', 'Quiz context'), ('QT', 'Quiz target'), ('QO', 'Quiz options'), ('QI', 'Quiz incorrect answer'), ('SK', 'Selection known'), ('SU', 'Selection unknown')], max_length=2)),
                ('learner', models.ForeignKey(help_text='Learner who encountered the Word', on_delete=django.db.models.deletion.CASCADE, related_name='enocounters', to='dance.learner')),
                ('word', models.ForeignKey(help_text='Word encountered by Learner', on_delete=django.db.models.deletion.CASCADE, related_name='enocounters', to='dance.word')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QZ', 'Quiz'), ('FS', 'Familiar selection'), ('KS', 'Known selection')], max_length=2)),
                ('questions', models.TextField(blank=True, help_text='Questions in JSON Schema format', null=True)),
                ('correct_answers', models.TextField(blank=True, help_text='Correct answers in JSON format matching schema in Questions', null=True)),
                ('learner_answers', models.TextField(blank=True, help_text='Answers by Learner in JSON format matching schema in Questions', null=True)),
                ('score', models.IntegerField(help_text='Percentage of correct responses', null=True)),
                ('learner', models.ForeignKey(help_text='Responding Learner', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dance.learner')),
            ],
        ),
    ]
