# Generated by Django 4.1.4 on 2023-01-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='stack_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stack',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='dance.collection'),
        ),
        migrations.AddField(
            model_name='stack',
            name='excluded_words',
            field=models.ManyToManyField(blank=True, related_name='stacks_excluded', to='dance.word'),
        ),
        migrations.AddField(
            model_name='stack',
            name='language',
            field=models.CharField(choices=[('KY', 'KYRGYZ'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], default='EN', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stack',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='stacks', to='dance.word'),
        ),
        migrations.AlterUniqueTogether(
            name='stack',
            unique_together={('learner', 'language', 'collection')},
        ),
    ]
