# Generated by Django 4.1.8 on 2023-05-11 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='system',
            field=models.ForeignKey(default=1, help_text='System of learners', on_delete=django.db.models.deletion.CASCADE, related_name='answersheets', to='dance.system'),
            preserve_default=False,
        ),
    ]
