# Generated by Django 4.1.4 on 2023-02-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0002_answersheet_stack_size_stack_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='clear_excluded',
            field=models.BooleanField(default=False, help_text='Flag indicating that Stack Answersheet is using to make questions should clear its Excluded field. It lead to Answersheet using all Words from Stack.'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='regenerate_stack',
            field=models.BooleanField(default=False, help_text='Flag indicating that Stack Answersheet is using to make questions should be regenerated'),
        ),
    ]
