# Generated by Django 4.1.4 on 2023-01-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0003_answersheet_uischema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='correct_answers',
            field=models.JSONField(default={}, help_text='Correct answers in JSON format matching schema in Questions'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='learner_answers',
            field=models.JSONField(default={}, help_text='Answers by Learner in JSON format matching schema in Questions'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='questions',
            field=models.JSONField(default={}, help_text='Questions in JSON Schema format'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='uischema',
            field=models.JSONField(default={}, help_text='UI schema for Questions in JSON Schema React Form format'),
        ),
    ]
