# Generated by Django 4.1.4 on 2023-02-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0003_answersheet_clear_excluded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='clear_excluded',
            field=models.BooleanField(blank=True, default=False, help_text='Flag indicating that Stack Answersheet is using to make questions should clear its Excluded field. It lead to Answersheet using all Words from Stack.'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='regenerate_stack',
            field=models.BooleanField(blank=True, default=False, help_text='Flag indicating that Stack Answersheet is using to make questions should be regenerated'),
        ),
    ]
