# Generated by Django 4.1.4 on 2023-02-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0004_alter_answersheet_clear_excluded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='review',
            field=models.BooleanField(blank=True, default=False, help_text='Flag indicating that generated Answersheet will be used for review and correctly answered questions will not be excluded from Stack.'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='clear_excluded',
            field=models.BooleanField(blank=True, default=False, help_text='Flag indicating that Stack Answersheet is using to make questions should clear its Excluded field. It leads to Answersheet using all Words from Stack.'),
        ),
    ]
