# Generated by Django 4.1.4 on 2023-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0005_alter_answersheet_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('KY', 'KYRGYZ'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(help_text='Translations of the word into other languages and synonyms', to='dance.word'),
        ),
    ]
