# Generated by Django 4.1.4 on 2023-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0006_word_language_word_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
