# Generated by Django 4.1.4 on 2023-01-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0007_word_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='native_language',
            field=models.CharField(choices=[('KY', 'KYRGYZ'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='test_language',
            field=models.CharField(choices=[('KY', 'KYRGYZ'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], default='EN', max_length=2),
        ),
    ]
