# Generated by Django 4.1.4 on 2023-01-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0008_answersheet_native_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, help_text='Translations of the word into other languages and synonyms', to='dance.word'),
        ),
    ]
