# Generated by Django 4.1.4 on 2023-01-27 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0009_alter_word_description_alter_word_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='learner',
            field=models.ForeignKey(help_text='Learner who encountered the Word', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='dance.learner'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='word',
            field=models.ForeignKey(help_text='Word encountered by Learner', on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='dance.word'),
        ),
    ]
