# Generated by Django 4.1.4 on 2023-01-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0010_alter_encounter_learner_alter_encounter_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack', to='dance.learner')),
                ('words', models.ManyToManyField(blank=True, to='dance.word')),
            ],
        ),
    ]
